name: investing_analytics
version: "1.0.0"
config-version: 2

profile: investing_analytics

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  investing_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +schema: analytics
