"""Investing analysis package."""

from .data_fetch.investing_com import (
    find_stock,
    get_stock_data,
    merge_stock_histories,
    resolve_yahoo_symbol,
    search_stocks,
)
from .data_fetch.stock_universe import fetch_stock_universe
from .data_fetch.market_intelligence import fetch_financial_statements, fetch_stock_news
from .db.store import (
    init_db,
    query_financial_statement_trends,
    query_fundamental_snapshots,
    query_latest_analysis_snapshots,
    query_stock_news_bulk,
    query_stock_history,
    query_stock_history_coverage,
    query_stock_histories,
    query_stock_news,
    query_stock_universe,
    query_stock_universe_symbols,
    save_analysis_snapshots,
    save_fundamental_snapshot,
    save_financial_statements,
    save_news_articles,
    save_stock_history,
    save_stock_universe,
)
from .core.html_report import generate_watchlist_report
from .core.cluster_report import generate_cluster_report
from .core.news_sentiment import score_news_text, summarize_stock_news
from .core.cluster_optimizer import optimize_stock_clusters, silhouette_score
from .core.clustering import (
    agglomerative_cluster_solutions,
    build_close_price_matrix,
    build_stock_similarity,
    cluster_by_correlation,
    cluster_distance_matrix,
    cluster_network_layout,
    cluster_relationship_summary,
    compute_return_correlation,
    compute_performance_similarity,
    compute_fundamental_similarity,
    correlation_pairs,
    nearest_cluster_edges,
)
from .core.ranking import (
    build_rankings,
    build_sector_fundamental_score,
    sector_profile_frame,
    top_dividend_recommendations_by_country,
    top_stocks_by_country_sector,
)
from .core.portfolio import analyze_stock, analyze_stocks
from .core.watchlist import analyze_watchlist, append_watchlist_rows, read_watchlist, write_watchlist
from .core.stock_analyzer import compute_stock_metrics, build_scorecard
from .core.stock_analysis import (
    altman_z_zone,
    calculate_altman_z_score,
    compute_dividend_history_metrics,
    merge_fundamentals,
)

__all__ = [
    "find_stock",
    "get_stock_data",
    "merge_stock_histories",
    "resolve_yahoo_symbol",
    "search_stocks",
    "fetch_stock_universe",
    "fetch_financial_statements",
    "fetch_stock_news",
    "init_db",
    "save_stock_history",
    "save_fundamental_snapshot",
    "save_financial_statements",
    "save_news_articles",
    "save_analysis_snapshots",
    "save_stock_universe",
    "query_stock_history",
    "query_stock_history_coverage",
    "query_stock_histories",
    "query_stock_news",
    "query_financial_statement_trends",
    "query_fundamental_snapshots",
    "query_latest_analysis_snapshots",
    "query_stock_news_bulk",
    "query_stock_universe",
    "query_stock_universe_symbols",
    "analyze_stock",
    "analyze_stocks",
    "analyze_watchlist",
    "append_watchlist_rows",
    "read_watchlist",
    "write_watchlist",
    "generate_watchlist_report",
    "generate_cluster_report",
    "score_news_text",
    "summarize_stock_news",
    "optimize_stock_clusters",
    "silhouette_score",
    "agglomerative_cluster_solutions",
    "build_close_price_matrix",
    "build_stock_similarity",
    "compute_return_correlation",
    "compute_performance_similarity",
    "compute_fundamental_similarity",
    "cluster_by_correlation",
    "cluster_distance_matrix",
    "cluster_network_layout",
    "cluster_relationship_summary",
    "correlation_pairs",
    "nearest_cluster_edges",
    "build_rankings",
    "build_sector_fundamental_score",
    "sector_profile_frame",
    "top_dividend_recommendations_by_country",
    "top_stocks_by_country_sector",
    "compute_stock_metrics",
    "build_scorecard",
    "calculate_altman_z_score",
    "altman_z_zone",
    "merge_fundamentals",
    "compute_dividend_history_metrics",
]
