select
    snapshot_date,
    upper(ticker) as ticker,
    lower(country) as country,
    name,
    exchange,
    data_source,
    market_cap,
    pe_ratio,
    eps,
    try_cast(replace(dividend_yield, '%', '') as double)
        / case when dividend_yield like '%\%%' then 100 else 1 end as dividend_yield,
    beta,
    revenue,
    sector,
    industry,
    revenue_growth,
    earnings_growth,
    return_on_equity,
    return_on_assets,
    profit_margins,
    operating_margins,
    debt_to_equity,
    current_ratio,
    free_cashflow,
    free_cashflow_yield,
    price_to_book,
    enterprise_to_ebitda,
    peg_ratio,
    payout_ratio,
    funds_from_operations,
    funds_from_operations_yield,
    altman_z_score,
    altman_z_zone,
    dividend_years_paid,
    consecutive_dividend_years,
    dividend_cagr_5y,
    latest_dividend_year
from {{ source('raw', 'fundamental_snapshot') }}
